apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: graphql-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: graphql
spec:
  hosts:
  - "*"
  gateways:
  - graphql-gateway
  http:
  - match:
    - uri:
        prefix: /ui
    - uri:
        prefix: /query
    route:
    - destination:
        host: graphql
        port:
          number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
    service: graphql
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: graphql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app: graphql
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
      version: v1
  template:
    metadata:
      labels:
        app: graphql
        version: v1
    spec:
      containers:
      - name: graphql
        image: localhost:5000/graphql:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080